test: Run with Poetry
On all supported Python versions. Python 3.10 did *not* work because of
an error building rasterio:

> rasterio/_warp.cpp:43950:19: error: ‘_PyGen_Send’ was not declared in
> this scope; did you mean ‘_PyGen_yf’?

Need to run on a specific Ubuntu version to avoid GDAL version drift.